[package]
name = "signet-node-config"
description = "Environment-driven configuration for the Signet node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
signet-blobber.workspace = true
signet-cold.workspace = true
signet-hot.workspace = true
signet-journal-chain.workspace = true
signet-rpc.workspace = true
signet-storage.workspace = true
signet-types.workspace = true

init4-bin-base.workspace = true

alloy.workspace = true

eyre.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
tracing.workspace = true
signet-genesis.workspace = true


[features]
test_utils = ["signet-rpc/test-utils"]
postgres = ["signet-storage/postgres", "signet-rpc/postgres", "init4-bin-base/cold-sql"]
sqlite = ["signet-storage/sqlite", "signet-rpc/sqlite", "init4-bin-base/cold-sql"]
